apiVersion: v1
kind: Service
metadata:
  name: project-name
  labels:
    app.kubernetes.io/name: project-name
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: project-name
  ports:
    - name: http
      port: 80
      targetPort: http
